[package]
name = "rust-mq"
version = "0.1.0"
authors = ["Maksim V. <inre.storm@gmail.com>"]
description = "RustMQ is the MQTT broker written on pure Rust."
license = "MIT"
keywords      = ["MQTT", "publish", "subscribe", "broker", "pubsub"]
exclude       = [
  ".gitignore",
  ".travis.yml",
  "test/**/*",
  "tmp/**/*"
]

[dependencies]
